version: "3"

services:
  web:
    build:
      context: .
    ports:
      - target: 8080
        published: 8080
    environment:
      PROTOCOL: 'http:'
      HOSTNAME: localhost
      PORT: 8080
      PATHNAME: /example-ang/
      API_ROOT: https://localhost/api
      AUTH_URL: https://localhost/auth
      AUTH_REALM: backbase
      AUTH_SCOPE: openid
      AUTH_CLIENT_ID: bb-web-client
      AUTH_LANDING_PAGE: select-context
      AUTH_REDIRECT_PAGE: redirect